packages:
  - packages/*
  - examples/*

ignoredBuiltDependencies:
  - nx

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild

shamefullyHoist: true

strictDepBuilds: true
minimumReleaseAge: 720 # twelve hours in minutes