packages:
  - packages/*
  - examples/*

ignoredBuiltDependencies:
  - nx

strictDepBuilds: true
minimumReleaseAge: 420 # 7 hours in minutes
minimumReleaseAgeExclude:
  - "@node-cli/*"
  - "@versini/*"
  - "@ai-sdk/*"
  - "ai"
  - npm-check-updates

onlyBuiltDependencies:
  - "@swc/core"
  - better-sqlite3
  - esbuild

shamefullyHoist: true
