packages:
  - packages/*
  - examples/*

strictDepBuilds: true
minimumReleaseAge: 420 # 7 hours in minutes
minimumReleaseAgeExclude:
  - "@node-cli/*"
  - "@versini/*"
  - "@ai-sdk/*"
  - "ai"
  - npm-check-updates

shamefullyHoist: true
allowBuilds:
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  nx: false
