packages:
  - packages/*
  - examples/*

ignoredBuiltDependencies:
  - nx

minimumReleaseAge: 720

minimumReleaseAgeExclude:
  - '@versini/dev-dependencies-common'
  - '@versini/dev-dependencies-server'
  - '@versini/dev-dependencies-types'

onlyBuiltDependencies:
  - '@swc/core'
  - better-sqlite3
  - esbuild

shamefullyHoist: true

strictDepBuilds: true
