name: Inspect Pull Requests

on:
  pull_request:
    branches: [main]

env:
  COREPACK_ENABLE_STRICT: 0
  COREPACK_INTEGRITY_KEYS: 0

jobs:
  inspect:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          corepack enable
          pnpm install
          pnpm turbo run build
          pnpm turbo run lint
          pnpm turbo run test:coverage
